---
- name: Scarica dati da GitHub API e crea un report
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Scarica dati pubblici da GitHub API
      ansible.builtin.uri:
        url: https://api.github.com
        return_content: yes
      register: github_api

    - name: Salva il JSON in un file
      copy:
        dest: ~/github_api.json
        content: "{{ github_api.content | default('') }}"

    - name: Fai parsing del JSON solo se possibile
      set_fact:
        github_api_parsed: "{{ github_api.content | from_json }}"
      when: github_api.content is defined

    - name: Estrai info solo se parsing riuscito
      set_fact:
        current_user_url: "{{ github_api_parsed.current_user_url | default('N/A') }}"
        emojis_url: "{{ github_api_parsed.emojis_url | default('N/A') }}"
      when: github_api_parsed is defined

    - name: Mostra le informazioni estratte
      debug:
        msg: |
          URL utente corrente: {{ current_user_url | default('N/A') }}
          URL emoji: {{ emojis_url | default('N/A') }}

    - name: Crea un report riassuntivo
      copy:
        dest: ~/github_api_report.txt
        content: |
          URL utente corrente: {{ current_user_url | default('N/A') }}
          URL emoji: {{ emojis_url | default('N/A') }}
