# filepath: /home/vmaximpopovschii/matplot/nginx_setup.yml
---
- name: Install and configure Nginx
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
            <h1>Hello from Semaphore & Ansible!</h1>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'
